### PR TITLE
API Custom rules for email recipients

### PR DESCRIPTION
**Pull request by tractorcow**
This enables custom rules for email recipients based on field values

### CODE REVIEW

**Comment by scott1702** [comment]
Love how things are split into tabs!

Few things 
• Rename some of the field titles and tabs
• Merge the email reply to/email send to fields into one. (Allowing both email fields and multi options fields in the dropdown.
• Create inline add new recipient button to allow for multiple email addresses 
• Custom Rules needs a description so the user understands what they actually do (I'll write one up soon)
image

**Comment by tractorcow** [comment]
>  Merge the email reply to/email send to fields into one. (Allowing both email fields and multi options fields in the dropdown.

This is hugely risky, since we would effectively be allowing the userform to act as an open email spamming tool. There's never a (valid) use case where the "to" field should be plain text entry.

> Create inline add new recipient button to allow for multiple email addresses 

Sure; What if we allow multiple emails in the same field? what if it was a multi-line text field? What would be best  for multiple entry?

**Comment by scott1702** [comment]
> Sure; What if we allow multiple emails in the same field? what if it was a multi-line text field? What would be best for multiple entry? 

comma separated emails in the text input would've been best, but how would someone add multiple email addresses using form fields? (ie email field + multioption field). That was the main reason for it

**Comment by scott1702** [comment]
I misinterpreted what the 'email reply to' field was for, updated wireframe
image

**Comment by tractorcow** [comment]
> comma separated emails in the text input would've been best, but how would someone add multiple email addresses using form fields? (ie email field + multioption field). That was the main reason for it

They would have to create a separate recipient object; Which is the object we are looking at now, I guess.

**Comment by tractorcow** [comment]
I've updated based on feedback.

By the way, if this PR is accepted, I'll create a new PR to the main fork, so don't worry about merging this one.

**Comment by scott1702** [comment]
Tests failed D: Also tabs need updated titles.

**Comment by tractorcow** [comment]
I've updated the tab titles and fixed the tests. :D

**Comment by tractorcow** [comment]
Er, I had to remove the unit tests for 4.0, because gridfieldextensions isn't supported on 4.x yet.

**Pull request closed without merging**
